### PR TITLE
Add partially appliable version of eval

### PR DESCRIPTION
**Pull request by ARandomOWL**
Useful for resolving f(x=0) for example.

### CODE REVIEW

**Comment by snowleopard** [comment]
Partial evaluation is useful, but I think the implementation can be simplified a lot if you add a `Monad Expr` instance. Then partial evaluation will be something like:
```haskell
partialEval :: (a -> Maybe Bool) -> Expr a -> Expr a
partialEval f expr = expr >>= substitute
  where
    substitute x = case f x of
        Just bool -> Val bool
        Nothing   -> Var x
```

**Comment by ARandomOWL** [comment]
I will investigate it, thanks for the feedback!

**Comment by ARandomOWL** [comment]
I've attempted to write a Monad instance of Expr but I don't really know what I'm doing. I don't know what the Applicative instance should look like, and I'm having type problems with `>>=`. Overall I'm not sure how to apply Monad to this problem.

**Comment by snowleopard** [comment]
@ARandomOWL I've pushed an implementation of Applicative and Monad.

Monad simply propagates the function to the leaves and applies it to the leaves. Applicative's `<*>` is implemented via Monad's `ap`.

Hope this helps!

By the way, I think it makes sense to move the definition of `Expr` to `Tuura.Boolean`. It's strange to see it defined in `Parser`. Note that this may break Plato, so it will need to be fixed too.

**Comment by ARandomOWL** [comment]
Thanks @snowleopard I'll close this PR and open a new one with a complete implementation and some restructuring.

**Pull request closed without merging**
